// data/curriculum.xlsx → src/data/curriculum.gen.js  (run by scripts/build.mjs, or: node scripts/curriculum.mjs)
// The build stops with a Thai error list when a word uses a key the student has not learned
// yet, or a character that cannot be typed on the Kedmanee keyboard.
import fs from 'fs';
import { createRequire } from 'module';
import { KEYMAP } from '../src/engine/keymap.js';
import { STAGES, LESSON_DEFS, SYM_ITEMS, FORBIDDEN, lessonIdOf, lessonName, stepsFor, stepTitle } from '../src/data/stages.js';

const require = createRequire(import.meta.url);
const XLSX = require('xlsx');

const XLSX_PATH = 'data/curriculum.xlsx';
const GEN_PATH = 'src/data/curriculum.gen.js';

const TYPEABLE = new Set(Object.values(KEYMAP).flat());
for (const c of FORBIDDEN) TYPEABLE.delete(c);
const clean = v => String(v ?? '').replace(/\s+/g, ' ').trim();
const pad = n => String(n).padStart(2, '0');

// Keys learned up to (and including) lesson n
export function learnedUpTo(n) {
  const set = new Set([' ']);
  for (const d of LESSON_DEFS) if (d.n <= n && d.keys) for (const c of d.keys) set.add(c);
  return set;
}

function sheetRows(ws, firstRow) {
  const out = [];
  if (!ws || !ws['!ref']) return out;
  const range = XLSX.utils.decode_range(ws['!ref']);
  for (let r = firstRow - 1; r <= range.e.r; r++) {
    const v = c => ws[XLSX.utils.encode_cell({ r, c })]?.v;
    out.push({ row: r + 1, A: v(0), B: v(1), C: v(2), E: v(4), F: v(5) });
  }
  return out;
}

export function convertCurriculum() {
  if (!fs.existsSync(XLSX_PATH)) throw new Error(`ไม่พบไฟล์ ${XLSX_PATH}`);
  const wb = XLSX.read(fs.readFileSync(XLSX_PATH), { type: 'buffer' });
  const errors = [], warnings = [];
  const WORDS = {}, LONG = {};

  for (const def of LESSON_DEFS.filter(d => d.type === 'new')) {
    const name = 'บท' + pad(def.n);
    const ws = wb.Sheets[name];
    if (!ws) { errors.push(`ไม่พบแท็บ ${name}`); continue; }
    const learned = learnedUpTo(def.n), newKeys = new Set(def.keys);
    const seen = new Set(), list = [];
    for (const r of sheetRows(ws, 4)) {
      const w = clean(r.B);
      if (!w || clean(r.E) !== '✓' || seen.has(w)) continue;
      seen.add(w);
      const bad = [...w].filter(c => !learned.has(c) || !TYPEABLE.has(c));
      if (w.includes(' ')) { errors.push(`${name} แถว ${r.row}: "${w}" มีเว้นวรรค — ใส่ทีละคำ`); continue; }
      if (bad.length) { errors.push(`${name} แถว ${r.row}: "${w}" ใช้ ${[...new Set(bad)].join(' ')} ซึ่งยังไม่ได้เรียน/พิมพ์ไม่ได้`); continue; }
      if (![...w].some(c => newKeys.has(c))) warnings.push(`${name}: "${w}" ไม่มีแป้นใหม่ของบท (ใช้เป็นคำทบทวน)`);
      list.push(w);
    }
    if (list.length < 8) errors.push(`${name}: มีคำ ✓ แค่ ${list.length} คำ (ต้องมีอย่างน้อย 8)`);
    WORDS[def.n] = list;
  }

  for (const [n, items] of Object.entries(SYM_ITEMS)) {
    const learned = learnedUpTo(Number(n));
    for (const it of items) {
      const bad = [...it].filter(c => !learned.has(c) || !TYPEABLE.has(c));
      if (bad.length) errors.push(`SYM_ITEMS บท ${n}: "${it}" ใช้ ${[...new Set(bad)].join(' ')} ซึ่งยังไม่ได้เรียน`);
    }
  }

  const ws9 = wb.Sheets['ด่าน9'];
  if (!ws9) errors.push('ไม่พบแท็บ ด่าน9');
  for (const r of sheetRows(ws9, 4)) {
    const text = clean(r.F), n = Number(r.A);
    if (!text || clean(r.E) !== '✓') continue;
    if (!LESSON_DEFS.some(d => d.n === n && d.type === 'long')) { errors.push(`ด่าน9 แถว ${r.row}: เลขบท "${r.A}" ต้องเป็น 30–34`); continue; }
    const bad = [...text].filter(c => !TYPEABLE.has(c));
    if (bad.length) { errors.push(`ด่าน9 แถว ${r.row} (${clean(r.B)}): มีตัวที่พิมพ์ไม่ได้ ${[...new Set(bad)].join(' ')}`); continue; }
    (LONG[n] ||= []).push({ id: clean(r.B) || ('row' + r.row), title: clean(r.C), text });
  }
  for (const d of LESSON_DEFS.filter(d => d.type === 'long'))
    if (!LONG[d.n]?.length) errors.push(`ด่าน9: บท ${d.n} ไม่มีข้อความที่เลือก ✓`);

  if (errors.length) throw new Error('curriculum.xlsx มีปัญหา:\n  - ' + errors.join('\n  - '));
  const body = '// AUTO-GENERATED from data/curriculum.xlsx by scripts/curriculum.mjs — do not edit by hand.\n' +
    'export const WORDS = ' + JSON.stringify(WORDS) + ';\n' +
    'export const LONG = ' + JSON.stringify(LONG) + ';\n';
  fs.writeFileSync(GEN_PATH, body);
  return { warnings, words: Object.values(WORDS).reduce((a, l) => a + l.length, 0), passages: Object.values(LONG).reduce((a, l) => a + l.length, 0) };
}

// Lesson list for teacher.html's weekly-test picker (written to dist/lesson-index.js).
export function lessonIndexJs() {
  const idx = STAGES.map(st => ({
    ch: st.id, title: `ด่าน ${st.id} — ${st.title}`,
    lessons: LESSON_DEFS.filter(d => d.stage === st.id).map(d => ({
      id: lessonIdOf(d.n), name: `${d.n} ${lessonName(d)}`,
      exs: stepsFor(d).map((s, i) => stepTitle(d, i, s)),
    })),
  }));
  return '// AUTO-GENERATED by scripts/curriculum.mjs\nwindow.ANSTH_LESSON_INDEX = ' + JSON.stringify(idx) + ';\n';
}

if (process.argv[1] && process.argv[1].endsWith('curriculum.mjs')) {
  const r = convertCurriculum();
  console.log(`curriculum: ${r.words} words, ${r.passages} passages`);
  if (r.warnings.length) console.log('  (เตือน) ' + r.warnings.slice(0, 20).join('\n  (เตือน) '));
}
